package at.vsa.backend.user.authentication.config;

import lombok.Getter;

@Getter
public enum Country {

    AFGHANISTAN(true, "AF", "Afghanistan"),
    ALBANIA(true, "AL", "Albania"),
    ALGERIA(true, "DZ", "Algeria"),
    ANDORRA(true, "AD", "Andorra"),
    ANGOLA(true, "AO", "Angola"),
    ANTIGUA_AND_BARBUDA(true, "AG", "Antigua and Barbuda"),
    ARGENTINA(true, "AR", "Argentina"),
    ARMENIA(true, "AM", "Armenia"),
    AUSTRALIA(true, "AU", "Australia"),
    AUSTRIA(true, "AT", "Austria"),
    AZERBAIJAN(true, "AZ", "Azerbaijan"),
    BAHAMAS(true, "BS", "Bahamas"),
    BAHRAIN(true, "BH", "Bahrain"),
    BANGLADESH(true, "BD", "Bangladesh"),
    BARBADOS(true, "BB", "Barbados"),
    BELARUS(true, "BY", "Belarus"),
    BELGIUM(true, "BE", "Belgium"),
    BELIZE(true, "BZ", "Belize"),
    BENIN(true, "BJ", "Benin"),
    BHUTAN(true, "BT", "Bhutan"),
    BOLIVIA(true, "BO", "Bolivia"),
    BOSNIA_AND_HERZEGOVINA(true, "BA", "Bosnia and Herzegovina"),
    BOTSWANA(true, "BW", "Botswana"),
    BRAZIL(true, "BR", "Brazil"),
    BRUNEI(true, "BN", "Brunei"),
    BULGARIA(true, "BG", "Bulgaria"),
    BURKINA_FASO(true, "BF", "Burkina Faso"),
    BURUNDI(true, "BI", "Burundi"),
    CABO_VERDE(true, "CV", "Cabo Verde"),
    CAMBODIA(true, "KH", "Cambodia"),
    CAMEROON(true, "CM", "Cameroon"),
    CANADA(true, "CA", "Canada"),
    CENTRAL_AFRICAN_REPUBLIC(true, "CF", "Central African Republic"),
    CHAD(true, "TD", "Chad"),
    CHILE(true, "CL", "Chile"),
    CHINA(true, "CN", "China"),
    COLOMBIA(true, "CO", "Colombia"),
    COMOROS(true, "KM", "Comoros"),
    CONGO(true, "CG", "Congo"),
    COSTA_RICA(true, "CR", "Costa Rica"),
    CROATIA(true, "HR", "Croatia"),
    CUBA(true, "CU", "Cuba"),
    CYPRUS(true, "CY", "Cyprus"),
    CZECH_REPUBLIC(true, "CZ", "Czech Republic"),
    DEMOCRATIC_REPUBLIC_OF_THE_CONGO(true, "CD", "Democratic Republic of the Congo"),
    DENMARK(true, "DK", "Denmark"),
    DJIBOUTI(true, "DJ", "Djibouti"),
    DOMINICA(true, "DM", "Dominica"),
    DOMINICAN_REPUBLIC(true, "DO", "Dominican Republic"),
    ECUADOR(true, "EC", "Ecuador"),
    EGYPT(true, "EG", "Egypt"),
    EL_SALVADOR(true, "SV", "El Salvador"),
    EQUATORIAL_GUINEA(true, "GQ", "Equatorial Guinea"),
    ERITREA(true, "ER", "Eritrea"),
    ESTONIA(true, "EE", "Estonia"),
    ESWATINI(true, "SZ", "Eswatini"),
    ETHIOPIA(true, "ET", "Ethiopia"),
    FIJI(true, "FJ", "Fiji"),
    FINLAND(true, "FI", "Finland"),
    FRANCE(true, "FR", "France"),
    GABON(true, "GA", "Gabon"),
    GAMBIA(true, "GM", "Gambia"),
    GEORGIA(true, "GE", "Georgia"),
    GERMANY(true, "DE", "Germany"),
    GHANA(true, "GH", "Ghana"),
    GREECE(true, "GR", "Greece"),
    GRENADA(true, "GD", "Grenada"),
    GUATEMALA(true, "GT", "Guatemala"),
    GUINEA(true, "GN", "Guinea"),
    GUINEA_BISSAU(true, "GW", "Guinea-Bissau"),
    GUYANA(true, "GY", "Guyana"),
    HAITI(true, "HT", "Haiti"),
    HONDURAS(true, "HN", "Honduras"),
    HUNGARY(true, "HU", "Hungary"),
    ICELAND(true, "IS", "Iceland"),
    INDIA(true, "IN", "India"),
    INDONESIA(true, "ID", "Indonesia"),
    IRAN(true, "IR", "Iran"),
    IRAQ(true, "IQ", "Iraq"),
    IRELAND(true, "IE", "Ireland"),
    ISRAEL(true, "IL", "Israel"),
    ITALY(true, "IT", "Italy"),
    IVORY_COAST(true, "CI", "Ivory Coast"),
    JAMAICA(true, "JM", "Jamaica"),
    JAPAN(true, "JP", "Japan"),
    JORDAN(true, "JO", "Jordan"),
    KAZAKHSTAN(true, "KZ", "Kazakhstan"),
    KENYA(true, "KE", "Kenya"),
    KIRIBATI(true, "KI", "Kiribati"),
    KOSOVO(true, "XK", "Kosovo"),
    KUWAIT(true, "KW", "Kuwait"),
    KYRGYZSTAN(true, "KG", "Kyrgyzstan"),
    LAOS(true, "LA", "Laos"),
    LATVIA(true, "LV", "Latvia"),
    LEBANON(true, "LB", "Lebanon"),
    LESOTHO(true, "LS", "Lesotho"),
    LIBERIA(true, "LR", "Liberia"),
    LIBYA(true, "LY", "Libya"),
    LIECHTENSTEIN(true, "LI", "Liechtenstein"),
    LITHUANIA(true, "LT", "Lithuania"),
    LUXEMBOURG(true, "LU", "Luxembourg"),
    MADAGASCAR(true, "MG", "Madagascar"),
    MALAWI(true, "MW", "Malawi"),
    MALAYSIA(true, "MY", "Malaysia"),
    MALDIVES(true, "MV", "Maldives"),
    MALI(true, "ML", "Mali"),
    MALTA(true, "MT", "Malta"),
    MARSHALL_ISLANDS(true, "MH", "Marshall Islands"),
    MAURITANIA(true, "MR", "Mauritania"),
    MAURITIUS(true, "MU", "Mauritius"),
    MEXICO(true, "MX", "Mexico"),
    MICRONESIA(true, "FM", "Micronesia"),
    MOLDOVA(true, "MD", "Moldova"),
    MONACO(true, "MC", "Monaco"),
    MONGOLIA(true, "MN", "Mongolia"),
    MONTENEGRO(true, "ME", "Montenegro"),
    MOROCCO(true, "MA", "Morocco"),
    MOZAMBIQUE(true, "MZ", "Mozambique"),
    MYANMAR(true, "MM", "Myanmar"),
    NAMIBIA(true, "NA", "Namibia"),
    NAURU(true, "NR", "Nauru"),
    NEPAL(true, "NP", "Nepal"),
    NETHERLANDS(true, "NL", "Netherlands"),
    NEW_ZEALAND(true, "NZ", "New Zealand"),
    NICARAGUA(true, "NI", "Nicaragua"),
    NIGER(true, "NE", "Niger"),
    NIGERIA(true, "NG", "Nigeria"),
    NORTH_KOREA(true, "KP", "North Korea"),
    NORTH_MACEDONIA(true, "MK", "North Macedonia"),
    NORWAY(true, "NO", "Norway"),
    OMAN(true, "OM", "Oman"),
    PAKISTAN(true, "PK", "Pakistan"),
    PALAU(true, "PW", "Palau"),
    PANAMA(true, "PA", "Panama"),
    PAPUA_NEW_GUINEA(true, "PG", "Papua New Guinea"),
    PARAGUAY(true, "PY", "Paraguay"),
    PERU(true, "PE", "Peru"),
    PHILIPPINES(true, "PH", "Philippines"),
    POLAND(true, "PL", "Poland"),
    PORTUGAL(true, "PT", "Portugal"),
    QATAR(true, "QA", "Qatar"),
    ROMANIA(true, "RO", "Romania"),
    RUSSIA(true, "RU", "Russia"),
    RWANDA(true, "RW", "Rwanda"),
    SAINT_KITTS_AND_NEVIS(true, "KN", "Saint Kitts and Nevis"),
    SAINT_LUCIA(true, "LC", "Saint Lucia"),
    SAINT_VINCENT_AND_THE_GRENADINES(true, "VC", "Saint Vincent and the Grenadines"),
    SAMOA(true, "WS", "Samoa"),
    SAN_MARINO(true, "SM", "San Marino"),
    SAO_TOME_AND_PRINCIPE(true, "ST", "Sao Tome and Principe"),
    SAUDI_ARABIA(true, "SA", "Saudi Arabia"),
    SENEGAL(true, "SN", "Senegal"),
    SERBIA(true, "RS", "Serbia"),
    SEYCHELLES(true, "SC", "Seychelles"),
    SIERRA_LEONE(true, "SL", "Sierra Leone"),
    SINGAPORE(true, "SG", "Singapore"),
    SLOVAKIA(true, "SK", "Slovakia"),
    SLOVENIA(true, "SI", "Slovenia"),
    SOLOMON_ISLANDS(true, "SB", "Solomon Islands"),
    SOMALIA(true, "SO", "Somalia"),
    SOUTH_AFRICA(true, "ZA", "South Africa"),
    SOUTH_KOREA(true, "KR", "South Korea"),
    SOUTH_SUDAN(true, "SS", "South Sudan"),
    SPAIN(true, "ES", "Spain"),
    SRI_LANKA(true, "LK", "Sri Lanka"),
    SUDAN(true, "SD", "Sudan"),
    SURINAME(true, "SR", "Suriname"),
    SWEDEN(true, "SE", "Sweden"),
    SWITZERLAND(true, "CH", "Switzerland"),
    SYRIA(true, "SY", "Syria"),
    TAIWAN(true, "TW", "Taiwan"),
    TAJIKISTAN(true, "TJ", "Tajikistan"),
    TANZANIA(true, "TZ", "Tanzania"),
    THAILAND(true, "TH", "Thailand"),
    TOGO(true, "TG", "Togo"),
    TONGA(true, "TO", "Tonga"),
    TRINIDAD_AND_TOBAGO(true, "TT", "Trinidad and Tobago"),
    TUNISIA(true, "TN", "Tunisia"),
    TURKEY(true, "TR", "Turkey"),
    TURKMENISTAN(true, "TM", "Turkmenistan"),
    TUVALU(true, "TV", "Tuvalu"),
    UGANDA(true, "UG", "Uganda"),
    UKRAINE(true, "UA", "Ukraine"),
    UNITED_ARAB_EMIRATES(true, "AE", "United Arab Emirates"),
    UNITED_KINGDOM(true, "GB", "United Kingdom"),
    UNITED_STATES(true, "US", "United States"),
    URUGUAY(true, "UY", "Uruguay"),
    UZBEKISTAN(true, "UZ", "Uzbekistan"),
    VANUATU(true, "VU", "Vanuatu"),
    VATICAN_CITY(true, "VA", "Vatican City"),
    VENEZUELA(true, "VE", "Venezuela"),
    VIETNAM(true, "VN", "Vietnam"),
    YEMEN(true, "YE", "Yemen"),
    ZAMBIA(true, "ZM", "Zambia"),
    ZIMBABWE(true, "ZW", "Zimbabwe");

    private final boolean legal;
    @Getter
    private final String name;
    private final String cc;

    Country(boolean legal, String cc, String name) {
        this.legal = legal;
        this.cc = cc;
        this.name = name;
    }

    public static boolean isValid(String country) {
        for (Country c : Country.values()) {
            if (c.legal && c.cc.equals(country)) {
                return true;
            }
        }
        return false;
    }

    public static Country getCountryByCC(String cc) {
        for (Country code : Country.values()) {
            if (code.cc.equals(cc)) {
                return code;
            }
        }
        return null;
    }
}
